# Generated by Django 2.2.4 on 2019-08-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('micropythons', models.IntegerField()),
                ('minipythons', models.IntegerField()),
            ],
        ),
    ]
