# Generated by Django 2.2.4 on 2019-08-06 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='minipythons',
            new_name='curlyboi_snektions',
        ),
    ]
